== ETC

클래스가 구현하는 인터페이스를 지정하기 위해서 콜론(:) 뒤에 인터페이스 이름을 사용한다.

=== is 스마트 캐스트: 타입 검사와 타입 캐스트의 조합

코틀린에서는 is 를 사용해 변수 타입을 검사한다.  +
어떤 변수가 원하는 타입인지 일단 is 로 검사하고 나면 굳이 변수를 원하는 타입으로 캐스팅하지 않아도 마치 처음부터 그 변수가 원하는 타입으로 선언된 것처럼 사용할 수 있다. +
실제로느느 컴파일러가 캐스팅을 수행해준다. +
이를 스마트 캐스트(Smart Cast)라고 부른다. + 

스마트 캐스트는 is 로 변수에 든 값의 타입을 검사한 다음에 그 값이 바뀔 수 없는 경우에만 작동한다. +
예를 틀어 클래스의 프로퍼티에 대해 스마트 캐스트를 사용한다면 그 프로퍼티는 반드시 val 이어야 하며, 커스텀 접근자를 사용한 것이어도 안 된다. val 이 아니거나 val 이지만 커스텀 접근자를 사용하는 경우에는 해당 프로퍼티에 대한 접근이 항상 같은 값을 내놓는다고 확신할 수 없기 때문이다. +

원하는 타입으로 명시적으로 타입 캐스팅하려면 as 키워드를 사용한다.

=== 블록의 마지막 식이 블록의 결과

이 규칙은 블록이 값을 만들어내야 하는 경우 항상 성립한다. +
이 규칙은 함수에 대해서는 성립하지 않는다. +
식이 본문인 함수는 블록을 본문으로 가질 수 없고, 블록이 본문인 함수는 내부에 return 문이 반드시 있어야 한다.

=== while 과 for

코틀린 while 루프는 자바와 동일하다. +
코틀린 for 는 자바의 for-each 루프에 해당하는 형태만 존재한다.

=== 범위

[source,kotlin]
----
val oneToTen = 1..0
----

코틀린의 범위는 폐구간(닫힌 구간) 또는 양끝을 포함하는 구간이다.

[source,kotlin]
----
for (i in 1..100)
...
----

[source,kotlin]
----
for (i in 100 downTo 1 step 2)
...
----

downTo 는 역방향 수열을 만든다(역방향 수열의 기본 증가값은 -1 이다). +
step 2 를 붙이면 증가값의 절대값이 2 로 바뀐다(이때 증가값의 방향은 바뀌지 않는다. 따라서 위의 경우 증가값은 실제로는 -2 와 같다).

until 은 열린구간 또는 뒤쪽 끝을 포함하지 않는다.

[source,kotlin]
----
for (x in 0 until size) 
...
----

은 다음과 같다.

[source,kotlin]
----
for (x in 0..size - 1)
---- 

=== 구조 분해

구조 분해 구문을 컬렉션에 활용할 수 있다. +
구조 분해 구문을 사용하면 원소의 현재 인덱스를 유지하면서 컬렉션을 이터레이션할 수 있다. +
인덱스를 저장하기 위한 변수를 별도로 선언하고 루프에서 매번 그 변수를 증가시킬 필요가 없다.

.DestructuringForList.kt
[source,kotlin]
----
package chap07

fun main(args: Array<String>) {
    val list = arrayListOf("10", "11", "1001")

    for((index, element) in list.withIndex()) {
        println("$index: $element")
    }
}
----

.DestructuringForMap.kt
[source,kotlin]
----
package chap07

import java.util.*

fun main(args: Array<String>) {
    val binaryRepo = TreeMap<Char, String>()

    for (c in 'A'..'F') {
        val binary = Integer.toBinaryString(c.toInt())
        binaryRepo[c] = binary
    }

    for ((letter, binary) in binaryRepo) {
        println("$letter = $binary")
    }
}
----

=== in 으로 컬렉션이나 범위의 원소 검사

in 연산자를 사용해 어떤 값이 범위에 속하는지 검사할 수 있다. +
반대로 !in 을 사용하면 어떤 값이 범위에 속하지 않는지 검사할 수 있다.

.InTest.kt
[source,kotlin]
----
package chap07

fun isLetter(c: Char) = c in 'a'..'z' || c in 'A'..'Z'

fun isNotDigit(c: Char) = c !in '0'..'9'

fun recognize(c: Char) = when (c) {
    in '0'..'9' -> "It's a digit!"
    in 'a'..'z', in 'A'..'Z' -> "It's a letter!"
    else -> "I don't know..."
}

fun main(args: Array<String>) {
    println(isLetter('q'))
    println(isNotDigit('x'))
    println(recognize('8'))
}
----

밤위는 문자에만 국한되지 않는다. +
비교가 가능한 클래스라면(java.lnag.Comparable 인터페이스를 구현한 클래스라면) 그 클래스의 인스턴스 객체를 사용해 범위를 만들 수 있다. +

Comparable 을 사용하는 범위의 경우 그 범위 내의 모든 객체를 항상 이터레이션하지는 못한다. +
예를 틀어 'Java' 와 'Kotlin' 사이의 모든 문자열을 이터레이션할 수 있을까? 그럴 수 없다. + 
하지만 in 연산자를 사용하면 값이 범위 안에 속하는지 항상 결정할 수 있다. +

컬렉션에도 마찬가지로 in 연산을 사용할 수 있다.