== 클래스 

- 클래스는 기본적으로 #public final# 이다.
- 클래스를  #data# 로 선언하면 컴파일러가 일부 표준 메소드를 생성해 준다.
- 클래스와 인스턴스를 동시에 선언하면서 만들 때는 #object# 키워드를 사용한다.
- #sealed# 는 클래스 상속을 제한한다.

=== 인터 페이스 

- override 변경자는 상위 클래스나 상위 인터페이스에 있는 프로퍼티나 메소드를 오버라이드한다는 표시이며, 필수이다.
- 디폴트 구현을 제공할 수 있다. 이때 어떤 변경자도 필요없다.
- super<Clickable>.showOff() 처럼 상위 타입의 이름을 꺽쇠 괄호 사이에 넣어서 어떤 상위 타입의 멤버 메소드를 호출할 지 지정할 수 있다.
.. 자바에서는 Clickable.super.showOff() 처럼 super 앞에 기반 타입을 적는다.
.. 자바에서는 코틀린의 디폴트 메소드 구현에 의존할 수 없다(자바에서 호출할 수 없다).

=== open, final, abstract 변경자 

코틀린의 클래스와 메소드는 기본적으로 final 이다.

어떤 클래스의 상속을 허용하려면 클래스 앞에 open 변경자를 붙여아 한다. +

오버라이드를 허용하고 싶은 메소드나 프로퍼티의 앞에도 open 변경자를 붙여야 한다. +
override 된 메소드는 자동으로 open 이다. +
override 된 메소드를 하위 클래스에서 override 를 금지하러면 final 키워드를 명시해야 한다.

.Code002.kt
[source,kotlin]
----
package chap13

open class RichButton: Clickable {
    fun disable() {}
    
    open fun animate() {}
    
    override fun click() {}
}
----

TIP: 클래스의 프로퍼티의 경우 val 이면서 커스텀 접근자가 없는 경우에만 스마트 캐스트를 쓸 수 있다.

추상 클래스에 속했더라도 비추상 함수는 기본적으로 final 이지만, 원한다면 open 으로 오버라이드 할 수 있다.

=== 가시성 변경자: public, internal, protected, private

.코틀린 가시성 변경자
|===
|변경자|클래스 멤버|최상위 선언
|public(기본)||
|internal|같은 모듈에서만|같은 모듈에서만
|protected|하위 클래스에서만|[red]#적용 불가#
|private|같은 #클래스# 안에서만|같은 #파일# 안에서만
|===

확장 함수는 그 클래스의 private 이나 protected 멤버에 접근할 수 없다.

코틀린에서는 외부 클래스가 내부 클래스나 중첩된 클래스의 private 멤버에 접근할 수 없다.

=== 내부 클래스와 중첩된 클래스: 기본적으로 중첩 클래스

코틀린의 중첩 클래스(nested class)는 명시적으로 요청하지 않는 한 바깥쪽 클래스 인스턴스에 대한 접근 권한이 없다.

코틀린 중첩 클래스에 아무런 변경자가 붙지 않으면 자바 static 중첩 클래스와 같다. +
내부 클래스로 변경해서 바깥쪽 클래스에 대한 참조를 포함하게 만들고 싶다면 #inner# 변경자를 붙여야 한다.

.자바와 코틀린의 중첩 클래스와 내부 클래스의 관계
|===
|클래스 B 안에 정의된 클래스 A|자바에서는|코틀린에서는 
|중첩 클래스(바깥쪽 클래스에 대한 참조를 저장하지 않음)|static class A|class A
|내부 클래스(바깥쪽 클래스에 대한 참조를 저장함)|class A|#inner# class A
|===

중첩 클래스 안에는 바깥쪽 클래스에 대한 참조가 없지만 내부 클래스에는 있다. +
내부 클래스 A 안에서 바깥쪽 클래스에 B 에 대한 참조에 접근하려면 this@B 라고 써야 한다.

[source,kotlin]
----
package chap13

class B {
    inner class A {
        fun getOuterReference(): B = this@B
    }
}

fun main(args: Array<String>) {
    val b = B()
    val a = b.A()

    println(a.getOuterReference())
}
----

=== 봉인된 클래스: 클래스 계층 정의 시 계층 확장 제한 

봉인된 클래스는 다른 파일에 하위 클래스를 정의할 수 없다.

코틀린 컴파일러는 when 을 사용해 값을 검사할 때 꼭 디폴트 분기인 else 분기를 덧붙잉게 강제한다. +
sealed 클래스를 사용하면 이러한 제한을 피할 수 있다. + 
#봉인된 클래스는 같은 파일 안에서만 하위 클래스를 만들 수 있다. + 
데이터 클래스로 하위 클래스를 정의할 수도 있다. +
sealed 클래스는 자동으로 open 클래스가 된다.# +
주로 봉인된 클래스 내부에 하위 클래스를 정의한다. +
나중에 sealed 클래스의 상속 계층에 새로운 하위 클래스를 추가해도 when 식이 컴파일되지 않는다. 따라서 when 식을 고쳐야 한다는 사실을 쉽게 알 수 있다. 

TIP: interface 를 구현하는 경우 :(콜론) 뒤에 인터페이스명만 적는다. +
class 를 상속하는 경우 : 뒤에 상위 클래스의 생성자를 적는다. +
클래스 정의에 있는 상위 클래스 및 인터페이스 목록에서 이름 뒤에 괄호가 붙었는지 살펴보면 쉽게 기반 클래스와 인터페이스를 구별할 수 있다.

.Code004.kt
[source,kotlin]
----
package chap13

sealed class Expr {
    class Num(val value: Int) : Expr()
    class Sum(val left: Expr, val right: Expr) : Expr()
}

fun main(args: Array<String>) {
    println(eval(Expr.Num(7)))
    println(eval(Expr.Sum(Expr.Num(3), Expr.Num(5))))
}

fun eval(e: Expr) : Int =
        when (e) {
            is Expr.Num -> e.value
            is Expr.Sum -> eval(e.right) + eval(e.left)
        }
----

=== 생성자 

클래스를 정의하면서 주생성자를 작성할 수 있다.

[source,kotlin]
----
class User001 constructor(_nickname: String) {
    val nickname: String
    
    init {
        nickname = _nickname
    }
}
----

주 생성자는 별도의 코드를 포함할 수 없으므로 초기화 블록(init) 이 필요하다. +
필요하다면 클래스 안에 여러 초기화 블록을 선언할 수 있다.

위의 소스를 아래로 대체할 수 있다.

[source,kotlin]
----
class User002 constructor(_nickname: String) {
    val nickname = _nickname
}
----

프로퍼티를 초기화하는 식이나 초기화 블록 안에서만 주 생성자의 파라미터를 참조할 수 있다.

주 생성자 앞에 별다른 애노테이션이나 가시성 변경자가 없다면 constructor 를 생략해도 된다.

[source,kotlin]
----
class User003 (_nickname: String) {
    val nickname = _nickname
}
----

주 생성자의 파라미터로 프로퍼티를 초기화한다면 그 주 생성자 파라미터 이름 앞에 val/var 을 추가하는 방식으로 프로퍼티 정의와 초기화를 간략히 쓸 수 있다.

[source,kotlin]
----
class User004 (val nickname: String)
----

함수 파라미터와 마찬가지로 생성자 파라미터에도 디폴트 값을 정의할 수 있다.

[source,kotlin]
----
class User005 (val nickname: String = "Jane Doe")
----

#모든 생성자 파라미터에 디폴트 값을 지정하면 컴파일러가 자동으로 파라미터가 없는 생성자를 만들어준다.#

기반 클래스를 초기화하려면 기반 클래스 이름 뒤에 괄호를 치고 생성자 인자를 넘긴다.

[source,kotlin]
----
open class User006(val nickname: String)
class TwitterUser(nickname: String): User006(nickname)
----

별도의 생성자를 정의하지 않으면 자바와 마찬가지로 디폴트 생성자를 만들어 준다.

[source,kotlin]
----
class User007
----

어떤 클래스를 클래스 외부에서 인스턴스화하지 못하게 막고 싶다면 모든 생성자를 private 으로 만들면 된다.

[source,kotlin]
----
class Secretive private constructor() {}
----

TIP: 비공개 생성자에 대한 대안 +
정적 유틸리티 함수 대산 최상위 함수 +
싱글턴을 사용하고 싶으면 객체 선언 


=== 부생성자 

오버로드한 생성자가 필요한 상황 중 상당수는 코틀린의 디폴트 파라미터 값과 일므 붙은 인자 문법으로 사용해 해결할 수 있다.

[source,kotlin]
----

class User008 {
    constructor(name: String) { // 부생성자
        
    }
    
    constructor(name: String, age: Int) { // 부생성자
        
    }
}
----

클래스에 주 생성자가 없다면 모든 부 생성자는 반드시 상위 클래스를 초기화하거나 다른 생성자에게 생성을 위임해야 한다.

[source,kotlin]
----
class User009 {
    constructor(name: String): this(name, 23) { // 부생성자

    }

    constructor(name: String, age: Int): super() { // 부생성자

    }
}
----

더 나은 대안 

[source,kotlin]
----
class User010 (val name: String = "Jane Doe", val age: Int = 23)
----


==== 인터페이스에 선언된 프로퍼티 구현 

코틀린에서는 인터페이스에 추상 프로퍼티 선언을 넣을 수 있다.

[source,kotlin]
----
interface User {
    val nickname: String // Abstract Property
}

class PrivateUser(override val nickname: String) : User

class SubscribingUser(val email: String) : User {
    override val nickname : String
    get() = email.substringBefore('@')
}

class FacebookUser(val accountId: Int) : User {
    override val nickname = getFacebookName(accountId)
}

fun getFacebookName(accountId: Int) : String {
    return "Jane Dow"
}
----

인터페이스에는 추상 프로퍼티뿐 아니라 게터와 세터가 있는 프로퍼티를 선언할 수도 있다. 물론 그런 게터와 세터는 뒷받침하는 필드를 참조할 수 없다(뒷받침하는 필드가 있다면 인터페이스에 상태를 추가하는 셈인데 인터페이스는 상태를 저장할 수 없다).

[source,kotlin]
----
interface User01 {
    val email: String
    val nickname: String 
    get() = email.substringBefore('@')
}
----


==== 게터와 세터에서 뒷받침하는 필드에 접근 (field 식별자)

접근자의 본문에서는 field 라는 특별한 식별자를 통해 뒷받침하는 필드에 접근할 수 있다. +
게터에서는 field 값을 읽을 수만 있고, 세터에서는 field 값을 읽거나 쓸 수 있다.

==== 접근자의 가시성 변경 

접근자의 가시성은 기본적으로는 프로퍼티의 가시성과 같다. 하지만 원한다면 get 이나 set 앞에 가시성 변경자를 추가해서 접근자의 가시성을 변경할 수 있다.

[source,kotlin]
----
class LengthCounter {
    var counter: Int = 0
    private set
    
    fun addWord(word: String) {
        counter += word.length
    }
}
----