== 클래스 

- 클래스는 기본적으로 #public final# 이다.
- 클래스를  #data# 로 선언하면 컴파일러가 일부 표준 메소드를 생성해 준다.
- 클래스와 인스턴스를 동시에 선언하면서 만들 때는 #object# 키워드를 사용한다.
- #sealed# 는 클래스 상속을 제한한다.

=== 인터 페이스 

- override 변경자는 상위 클래스나 상위 인터페이스에 있는 프로퍼티나 메소드를 오버라이드한다는 표시이며, 필수이다.
- 디폴트 구현을 제공할 수 있다. 이때 어떤 변경자도 필요없다.
- super<Clickable>.showOff() 처럼 상위 타입의 이름을 꺽쇠 괄호 사이에 넣어서 어떤 상위 타입의 멤버 메소드를 호출할 지 지정할 수 있다.
.. 자바에서는 Clickable.super.showOff() 처럼 super 앞에 기반 타입을 적는다.
.. 자바에서는 코틀린의 디폴트 메소드 구현에 의존할 수 없다(자바에서 호출할 수 없다).

=== open, final, abstract 변경자 

코틀린의 클래스와 메소드는 기본적으로 final 이다.

어떤 클래스의 상속을 허용하려면 클래스 앞에 open 변경자를 붙여아 한다. +

오버라이드를 허용하고 싶은 메소드나 프로퍼티의 앞에도 open 변경자를 붙여야 한다. +
override 된 메소드는 자동으로 open 이다. +
override 된 메소드를 하위 클래스에서 override 를 금지하러면 final 키워드를 명시해야 한다.

.Code002.kt
[source,kotlin]
----
package chap13

open class RichButton: Clickable {
    fun disable() {}
    
    open fun animate() {}
    
    override fun click() {}
}
----

TIP: 클래스의 프로퍼티의 경우 val 이면서 커스텀 접근자가 없는 경우에만 스마트 캐스트를 쓸 수 있다.

추상 클래스에 속했더라도 비추상 함수는 기본적으로 final 이지만, 원한다면 open 으로 오버라이드 할 수 있다.

=== 가시성 변경자: public, internal, protected, private

|===
|변경자|클래스 멤버|최상위 선언
|public(기본)||
|internal|같은 모듈에서만|같은 모듈에서만
|protected|하위 클래스에서만|[red]#적용 불가#
|private|같은 #클래스# 안에서만|같은 #파일# 안에서만
|===

확장 함수는 그 클래스의 private 이나 protected 멤버에 접근할 수 없다.

코틀린에서는 외부 클래스가 내부 클래스나 중첩된 클래스의 private 멤버에 접근할 수 없다.

=== 내부 클래스와 중첩된 클래스: 기본적으로 중첩 클래스